"""empty message

Revision ID: f83a3fe3b102
Revises: ffdc0a98111c
Create Date: 2022-09-01 12:54:40.537378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83a3fe3b102'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_records', 'communication_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_records', sa.Column('communication_score', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
